"""Write the comp's dashed disc out as path data for the page to draw.

The disc bleeds off the right edge of two bands and straddles the seam with the band above.
It had been reaching the build as a bitmap cropped out of a rendered page, which is why it
softened at any zoom, why its dash rhythm never matched, and why it could only ever appear
inside one band instead of across the seam.

It is not a circle and its dashes are not a stroke: the outline is six freehand beziers, and
the dashes are 179 separate filled slivers with round ends. Nothing built out of border-radius
and a dashed border can land on that, which is why the CSS attempts before this failed. The
drawing is in the PDF, so it is read from there and emitted verbatim.

Usage: python tools/disque_asset.py
"""

from __future__ import annotations

from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parents[1]
PDF = (
    ROOT.parent
    / 'EU4Youth'
    / 'UI Web Design-20260807T094637Z-1-001'
    / 'UI Web Design'
    / 'a propos.pdf'
)

# The instance under the vision band's seam. The one over the territoires band is the same
# drawing at another place, so one copy of the data serves both.
SELECT = (1700, 2800, 2200, 3200)
OUT = ROOT / 'src' / 'data' / 'disque.ts'


def path_data(items, ox: float, oy: float, places: int = 2) -> str:
    def pt(p) -> str:
        return f'{round(p.x - ox, places):g} {round(p.y - oy, places):g}'

    out: list[str] = []
    here = None
    for item in items:
        if item[0] == 'l':
            start, end = item[1], item[2]
            if here != start:
                out.append(f'M{pt(start)}')
            out.append(f'L{pt(end)}')
            here = end
        elif item[0] == 'c':
            start, c1, c2, end = item[1], item[2], item[3], item[4]
            if here != start:
                out.append(f'M{pt(start)}')
            out.append(f'C{pt(c1)} {pt(c2)} {pt(end)}')
            here = end
    return ' '.join(out)


def main() -> None:
    x0, y0, x1, y1 = SELECT
    with pymupdf.open(PDF) as doc:
        chosen = [
            d
            for d in doc[0].get_drawings()
            if x0 <= (d['rect'].x0 + d['rect'].x1) / 2 <= x1
            and y0 <= (d['rect'].y0 + d['rect'].y1) / 2 <= y1
        ]

    box = chosen[0]['rect']
    for drawing in chosen[1:]:
        box |= drawing['rect']

    # Largest item count is the ring of dashes; the other is the outline.
    dashes = max(chosen, key=lambda d: len(d['items']))
    blue = min(chosen, key=lambda d: len(d['items']))

    def colour(drawing) -> str:
        return '#' + ''.join(f'{round(c * 255):02x}' for c in drawing['fill'])

    body = f'''/* Generated by tools/disque_asset.py from a propos.pdf — do not edit by hand.
 *
 * The comp's dashed disc, in its own coordinates. Not a circle: the outline is six freehand
 * beziers, and the ring is {len(dashes['items'])} separate filled slivers rather than a dashed stroke, which is
 * why it is carried as path data instead of being approximated with a border.
 */

export const DISQUE = {{
  /** The drawing's full size. Placements show only part of it: it bleeds off the page. */
  width: {box.width:.2f},
  height: {box.height:.2f},
  outline: '{path_data(blue['items'], box.x0, box.y0)}',
  dashes: '{path_data(dashes['items'], box.x0, box.y0)}',
  outlineFill: '{colour(blue)}',
  dashFill: '{colour(dashes)}',
}} as const
'''

    OUT.write_text(body, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)}  ({len(body)} bytes)')
    print(f'  art {box.width:.2f} x {box.height:.2f} at x {box.x0:.1f} y {box.y0:.1f}')
    print(f'  outline {colour(blue)} ({len(blue["items"])} curves)')
    print(f'  dashes  {colour(dashes)} ({len(dashes["items"])} slivers)')


if __name__ == '__main__':
    main()
