"""Generate the public intervention catalogue from the approved mapping workbook.

The source workbook exposes initiative names and locations but leaves its
classification columns empty. This exporter keeps only public-safe source fields
after whitespace and governorate normalization. It never invents Nature/Secteur
values and never exports contacts, phone numbers, emails, grant amounts, or
personal representative names.

Do not blindly re-run this against the live `interventions.ts`: the site file
already carries classified nature/sector values (706/706) that are not in the
xlsx. A fresh export would wipe those fields. Merge by id instead.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from openpyxl import load_workbook


ROOT = Path(__file__).resolve().parents[1]
SOURCE = (
    ROOT.parent
    / "EU4Youth"
    / "site web EU4Youth.org-20260811T205332Z-1-001"
    / "site web EU4Youth.org"
    / "Mapping interactif"
    / "fichier final"
    / "EU4Youth - tableau global de collecte données - 2026.xlsx"
)
OUTPUT = ROOT / "src" / "data" / "interventions.ts"

PROJECTS = {
    "Jeun'ESS": "jeuness",
    "Fe3il.a": "fe3ila",
    "Maghroum'in": "maghroumin",
    "Swafy": "swafy",
    "Go4Youth": "go4youth",
    "Irada4Youth": "irada4youth",
}

GOVERNORATE_ALIASES = {
    "La Manouba": "Manouba",
    "kasserine": "Kasserine",
    "Kef": "Le Kef",
    "Beja": "Béja",
    "Kebili": "Kébili",
    "Gabes": "Gabès",
    "Medenine": "Médenine",
    "Zaghouane": "Zaghouan",
    "Toute la Tunisie (bénéficiaires)": "Présence nationale",
    # Keep the regional label; CartePage expands it onto the four governorates.
    "Grand Tunis": "Grand Tunis",
}

PUBLIC_NAME_OVERRIDES = {
    # Preserve the public initiative name without republishing a natural person.
    349: "DADA",
}


def clean(value: object) -> str:
    if value is None:
        return ""
    return re.sub(r"\s+", " ", str(value).replace("\xa0", " ")).strip()


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f"Mapping source not found: {SOURCE}")

    sheet = load_workbook(SOURCE, read_only=True, data_only=True)[
        "INITIATIVES_BENEFICIAIRES"
    ]
    records: list[dict[str, object]] = []

    for row in sheet.iter_rows(min_row=4, max_col=15, values_only=True):
        identifier, project, governorate, locality, name = row[:5]
        project_name = clean(project)
        initiative_name = clean(name)
        if not initiative_name or project_name not in PROJECTS:
            continue

        governorate_name = clean(governorate)
        if not governorate_name or governorate_name == "None":
            governorate_name = "Localisation non renseignée"
        else:
            governorate_name = GOVERNORATE_ALIASES.get(
                governorate_name, governorate_name
            )

        source_id = int(identifier)
        records.append(
            {
                "id": source_id,
                "project": project_name,
                "projectSlug": PROJECTS[project_name],
                "governorate": governorate_name,
                "locality": clean(locality),
                "name": PUBLIC_NAME_OVERRIDES.get(source_id, initiative_name),
                "nature": "",
                "sector": "",
            }
        )

    records.sort(key=lambda item: (str(item["governorate"]), str(item["name"])))
    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    content = f"""// Generated by tools/extract_mapping.py from the approved 2026 mapping workbook.
// Public-safe fields only: no personal contacts, phone numbers or email addresses.
// Known natural-person labels are replaced with their public initiative name.
// Nature / sector stay empty until the source workbook is enriched.

export type Intervention = {{
  id: number
  project: string
  projectSlug: string
  governorate: string
  locality: string
  name: string
  nature: string
  sector: string
}}

export const INTERVENTIONS: Intervention[] = {payload}
"""
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {len(records)} public interventions to {OUTPUT}")


if __name__ == "__main__":
    main()
