"""Decode HTML entities and trim whitespace in interventions.ts names."""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / 'src' / 'data' / 'interventions.ts'
HEADER = """// Generated by tools/extract_mapping.py from the approved 2026 mapping workbook.
// Public-safe fields only: no personal contacts, phone numbers or email addresses.
// Known natural-person labels are replaced with their public initiative name.
// Nature / sector stay empty until the source workbook is enriched.

export type Intervention = {
  id: number
  project: string
  projectSlug: string
  governorate: string
  locality: string
  name: string
  nature: string
  sector: string
}

"""

text = PATH.read_text(encoding='utf-8')
match = re.search(r'export const INTERVENTIONS: Intervention\[\] = (\[.*\])\s*$', text, re.S)
if not match:
    raise SystemExit('INTERVENTIONS array not found')

data = json.loads(match.group(1))
changed = 0
for row in data:
    name = row.get('name', '')
    cleaned = html.unescape(name).strip()
    if cleaned != name:
        row['name'] = cleaned
        changed += 1

PATH.write_text(
    HEADER
    + 'export const INTERVENTIONS: Intervention[] = '
    + json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    + '\n',
    encoding='utf-8',
)
print(f'cleaned {changed} names; restored type header; total {len(data)}')
